spring:
  application:
    ui:
      title: Ronja CRM
      version: 1.1.0
  main:
    web-application-type: none

client:
  customers:
    base-url: http://localhost:8087/customers
  representatives:
    base-url: http://localhost:8087/representatives
