spring:
  application:
    ui:
      title: Ronja CRM
      version: 1.4.0
      # EN/SK
      localization: SK
  main:
    web-application-type: none

client:
  customers:
    base-url: https://beo-1975-ronja-server-nv9ri.ondigitalocean.app/customers
  representatives:
    base-url: https://beo-1975-ronja-server-nv9ri.ondigitalocean.app/representatives
  metals:
    base-url: https://beo-1975-ronja-server-nv9ri.ondigitalocean.app/metals
    limit:
      daily: 2
      weekly: 10
      monthly: 40