spring:
  application:
    ui:
      title: Ronja CRM
      version: 1.4.0
      # EN/SK
      localization: SK
  main:
    web-application-type: none
  threads:
    virtual:
      enabled: true

client:
  customers:
    base-url: http://localhost:8087/customers
  representatives:
    base-url: http://localhost:8087/representatives
  metals:
    base-url: http://localhost:8087/metals
    limit:
      daily: 2
      weekly: 10
      monthly: 40
