before_install:
  - chmod +x mvnw

language: java
install: true
jdk: openjdk17

script:
  - ./mvnw verify jacoco:report sonar:sonar
  - curl -L -o agent https://app.testcontainers.cloud/download/testcontainers-cloud-agent_linux_x86-64
  - chmod +x agent
  - ./agent &
  - ./agent wait
  - ./mvnw test-compile failsafe:integration-test failsafe:verify

notifications:
  email:
    recipients:
      - hugo.rad@gmail.com
    on_success: always
    on_failure: always
