sudo: required

services:
  - docker

before_install:
  - chmod +x mvnw

language: java
install: true
jdk: openjdk17

script:
  - ./mvnw verify
  - ./mvnw jacoco:report sonar:sonar
  - ./mvnw test-compile failsafe:integration-test failsafe:verify

notifications:
  email:
    recipients:
      - hugo.rad@gmail.com
    on_success: always
    on_failure: always
