sudo: required

services:
  - docker

before_install:
  - chmod +x mvnw

language: java
install: true
jdk: openjdk25

script:
  - ./mvnw verify
  - ./mvnw jacoco:report sonar:sonar

notifications:
  email:
    recipients:
      - hugo.rad@gmail.com
    on_success: always
    on_failure: always
