name: Build and Test

on:
  push:
  pull_request:

jobs:
  build-and-test:

    runs-on: ubuntu-20.04
    name: Build and Test the Application
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Setup Cache      
      uses: actions/cache@v2
      with:
        fetch-depth: 0
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        java-package: jdk

    - name: Run Tests
      run: ./mvnw verify

    - name: Run Code Analysis
      run: ./mvnw jacoco:report sonar:sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
